name: simple-gadget
version: '1.0'
type: gadget
summary: Simple gadget for classic devices
description: |
  This gadget enables classic devices to authenticate with serial vault.
grade: stable
confinement: strict

# This gadget is architecure-independent, only shell hooks
architectures:
  - all

parts:
  assets:
    plugin: nil
