#!/bin/sh

mkdir -p $SNAP_COMMON
exec >> $SNAP_COMMON/prepare-device-hook.log 2>&1
product_serial=`date -Is`
echo "product_serial:[$product_serial]"
snapctl set registration.proposed-serial="\"${product_serial}\""
snapctl set device-service.url="https://serial-vault.staging.canonical.com/v1/"
snapctl set device-service.headers='{"api-key": "A2Pp5mr8aOl0VlK7iVjqV6aOLY6JrSXAfGysGydBKkAsOf5Ct8ylSg"}'
