#!/bin/sh

mkdir -p $SNAP_COMMON
exec >> $SNAP_COMMON/prepare-device-hook.log 2>&1
product_serial=`date +%s`
echo "product_serial:[$product_serial]"
snapctl set registration.proposed-serial="\"${product_serial}\""
snapctl set device-service.url="https://serial-vault-partners.canonical.com/v1/"
snapctl set device-service.headers='{"api-key": "API-KEY-FROM-MODEL"}'
